### ISSUE TITLE
Add support for WebGL through Kni Engine

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1304]
This is a huge issue. I personally would love to see this happen, but it's unlikely to happen until after Kid Defense and Cthulhu are shipped unless someone else wants to jump on this and help get this going.

I'm creating an issue here for anyone who might want to help, and also to log this blog post that will be helpful.

https://darkgenesis.zenithmoon.com/monogame-on-the-web-No-really!.html

**Comment by nkast** [comment]
That might be helpful, [Migrating from MonoGame 3.8.1 to KNI 3.12](https://github.com/kniEngine/kni/blob/main/Documentation/articles/migrate_381.md).

**Comment by vchelaru** [comment]
This is in progress currently. 

To do:

- [x] Update all nuget actions to build/deploy
    - [x] Build templates
    - [x] Build engine .dlls and upload them
- [x] Add new entry to new project dropdown
- [x] Add support for content pipeline - do we need to run the kni pipeline manually for certain files like WAV? MP3? FX? Other?
- [x] Add synced project support
...
- [x] Get Cranky Chibi Cthulhu completely synced and running on itch



Blockers:
- [x] Kni Web gamepad support https://github.com/kniEngine/kni/issues/1620
- [x] Kni Web vertex offset in DrawUserPrimitives https://github.com/kniEngine/kni/issues/1721
- [x] Kni CTRL and SHIFT keys not being recognized https://github.com/kniEngine/kni/issues/1733
- [x] Kni Web DrawUserIndexedPrimitives support https://github.com/kniEngine/kni/issues/1737

**Comment by vchelaru** [comment]
I'm closing this issue as we've fully released FRB web. More to do here, but I'll create specific issues for it.
