### ISSUE TITLE
FlatRedBall Should Support Spine

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1320]
Spine is a robust keyframe and spriterigging animation program with a variety of runtimes. We intend to add support for Spine in FlatRedBall. Here are requirements in phases.

## Milestone 0: Content specific to FRB-style games

- [x] Create test project with animations and eval artist workflow
- [x] Add collision shapes to test project
- [x] Add multiple skeletons with unique animations to test project
- [x] Figure out how to use spritesheets in Spine
- [x] Figure out how to export Spine objects and preserve spritesheet
- [x] Add events to animations
- [x] Export content to FRB project for integration

## Milestone 1: Basic functionality and code integration

- [x] Create repo for FRB + Spine since it requires special licensing 
- [x] Integrate Spine MonoGame runtime
- [x] Load and render a Spine object in code
- [x] Play Spine animations in code
- [x] Use Spine polygon for FRB collision in code
- [x] Bind Spine event in code
- [x] Flipping on the X axis can be done in code and animations and collisions work as expected
- [x] Looping and one-off animations both work
- [x] Animation timing can be controlled in code (e.g. play at 10% speed)
- [x] TimeManager settings affect Spine animation speed
- [x] Game pausing affects Spine animations
- [x] Spine entities can "interleve" with FRB entities when rendering
- [x] ~Developer can swap sprite textures used by a Spine attachment in code~ Vic talked to Justin and we decided to look at this later.

## Milestone 2: Editor integration

- [x] User can add a spine skeleton export to an entity
- [x] FRB creates spine object instance
- [x] Spine polygons can be used to create collision relationships in the Editor
- [x] Spine events can be added as an Entity event in the Editor
- [x] Spine objects render correctly in the live editor

## Milestone 3: Performance and polish

- [x] 100 spine animations can play simultaneously at 30fps on an average laptop
- [x] Measure spine render breaks and add debug output
- [x] Look for any performance hotspots

## Milestone 4: Stretch Goals

- [x] Spine entities work in FNA-based FRB projects
- [x] ~Spine objects can work in Gum UI?~
- [x] Can create a spine Atlas file from FRB tooling (texture mapper in Glue? Animation Editor?)

**Comment by profexorgeek** [comment]
I have completed a Spine project that I think contains all of the main use cases.

Note that "skeleton" in the context of this comment means the Spine Skeleton data structure and not a skeleton in the visual appearance of the art sense.

Here are details:

## 1. Two Skeleton JSON Files
These files are `humanoid.json` and `treasure_chest.json` in the root of the content folder. These files reference `nardiak.atlas` which maps named sprites to the main `spritesheet.png` that is used in the rest of the FRB project. Each skeleton should be its own entity. One is a treasure chest, the other is a humanoid character.

## 2. Animations
Each skeleton has animations that you should be able to play programmatically
![image](https://github.com/vchelaru/FlatRedBall/assets/711100/652708d3-8470-4c23-bf99-0e8138d4b916)


## 3. Collision
Each skeleton has collision that should be able to be treated as a polygon by FRB.
![image](https://github.com/vchelaru/FlatRedBall/assets/711100/b0f00527-e98b-4304-a003-f92628b86009)


## 4. Events
The humanoid skeleton has a `damageStatus` event that fires during attack animations. It will have a string argument that is passed to the event handler. The string argument will be `"damageStart"` when the animation should deal damage, and a `"damageEnd"` when the animation should no longer deal damage.

![image](https://github.com/vchelaru/FlatRedBall/assets/711100/8b427bd8-1e1f-40b8-ae66-78c873dab486)

**Comment by vchelaru** [comment]
Adding additional technical requirements:

- [x] Atlas Texture loading should respect ContentManager specified in Screen/Entity
- [x] Fix one-frame delay on collision and flipping

**Comment by vchelaru** [comment]
I believe this is done. All Spine-related docs can be found here:

https://docs.flatredball.com/flatredball/spine
